### ISSUE TITLE
HTTP Error 413

### ISSUE THREAD

**Issue by FabianRup** [iquasere/UPIMAPI#1]
Hello, 

thank you for your nice tool, that allows easy UniprotID mapping. I am interested in mapping lots of UniProt IDs (12.5 million to be precise) to their EggNOG id. For this, I saved the UniprotIDs as a csv file with each UniprotID in a separate line. 
Having only 100 Ids and running the following command gives me the correct information already:

upimapi.py -i afdb_test.csv -o ~/Desktop/ -dbs "evolutionary genealogy of genes: Non-supervised Orthologous Groups"

However, as soon as I try the full input, I get the HTTP Error 413, which is I guess a too large request for the server. However, even using smaller steps such as --step 100, I get the same mistake. 

Do you have a suggestion how to solve this?

Thank you so much!
Fabian

**Comment by FabianRup** [comment]
Hello, 

I guess I solved the problem: I had all entrances separated by a comma AND a new line. The file needs to be a one-liner. 

Using the --fasta option, is it necessary for UPIMAPI to check if all UniprotIDs have been processed afterwards? It seems to take quite a long time.

Thank you!
Fabian

**Comment by iquasere** [comment]
As TL;DR - UPIMAPI accepts TXT IDs separated by commas, as in [here](https://github.com/iquasere/UPIMAPI/blob/master/ci/ids.txt), its help message is wrong.

UPIMAPI at first processed inputted TXT IDs as one ID per line, but then I thought it would be better to accept a single line of comma-separated values, similarly to how it accepts those values through the CLI.  However, I see that UPIMAPI's help message was never updated.

Today I will release a new version of UPIMAPI with that information updated. Thank you very much for bringing this to my attention!

As a final remark, UniProt is increasingly capable of taking large requests. Last time I tested the API's capacity, it was taking 50000 IDs at a time, with all default columns and databases of UPIMAPI (some 40 fields of information). So it really is just because of my distraction.
